array(
	'key' => 'field_dvrvqz18obp4p',
	'label' => "Autauga",
	'name' => "autauga",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_gss8x6cikk76w',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_oc8hge4u331ll',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_m1qygtv2cl71u',
	'label' => "Baldwin",
	'name' => "baldwin",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_t4yq33blndvwx',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_rzipdti9s27fp',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_o753k3rrvrf0b',
	'label' => "Barbour",
	'name' => "barbour",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_rgsulaf6q1u8h',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_9afvnt8i59dte',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_hcqrwxz5yf9c4',
	'label' => "Bibb",
	'name' => "bibb",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_n5ghyfx46c45w',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_p4yjkmj2sae36',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_gxotdahxulosn',
	'label' => "Blount",
	'name' => "blount",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_8so7i371que69',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_p6ughz0epl9iy',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_fqhteug9h1g3b',
	'label' => "Bullock",
	'name' => "bullock",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_87ahw2dtfaxzd',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_ehj851ijpm1s4',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_kqffexmm65x0h',
	'label' => "Butler",
	'name' => "butler",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_21g7a74hvbq5q',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_hz3mczcuiosjj',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_6n1ansclthsns',
	'label' => "Calhoun",
	'name' => "calhoun",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_ufb1fr8s6ru0t',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_sp6z2uhrr5zs2',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_332u49lhnnqbx',
	'label' => "Chambers",
	'name' => "chambers",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_gudwaannlvc9j',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_v50o4hn29ismg',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_zb0pd6fig5hme',
	'label' => "Cherokee",
	'name' => "cherokee",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_bjrtgk6as2h31',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_th171naedau0b',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_5duenako2y25k',
	'label' => "Chilton",
	'name' => "chilton",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_6hq2nmh4ppkko',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_90uei9q25nxhd',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_6o7xu82i93mi2',
	'label' => "Choctaw",
	'name' => "choctaw",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_r8nsceas9ulyg',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_dlom4wqeq839m',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_51tia1j0dkhyu',
	'label' => "Clarke",
	'name' => "clarke",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_3xp9e4bs8v2lc',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_203wlba7kciqz',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_x0u2edkixj2nq',
	'label' => "Clay",
	'name' => "clay",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_d22hch2yoggt8',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_4keuqiuik7hqk',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_wyor17kxxhkwv',
	'label' => "Cleburne",
	'name' => "cleburne",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_ztbwmkiz7tgd2',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_d7cfbzmijdn73',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_j9z4ysf2pn4qh',
	'label' => "Coffee",
	'name' => "coffee",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_7y98e31u9bgjr',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_5owts5cynxhq7',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_czley98yemtsd',
	'label' => "Colbert",
	'name' => "colbert",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_xibufl86pqd5x',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_fhtu8u2wpt1nj',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_ahikrip2nh6rj',
	'label' => "Conecuh",
	'name' => "conecuh",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_pym1o3a2j0yd2',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_8njnssmpbf0l0',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_m39fr3rvlx0gx',
	'label' => "Coosa",
	'name' => "coosa",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_34ok2c8evgm08',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_i4qd5o5kwwu1m',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_cqq2fw47rb7iu',
	'label' => "Covington",
	'name' => "covington",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_dwpkj2svsht1w',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_8mrf5rntgyj28',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_2eu1r17h7p9o4',
	'label' => "Crenshaw",
	'name' => "crenshaw",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_oio09oawqcxz6',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_ek0e7w2nyntjy',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_suq9g3kyamls2',
	'label' => "Cullman",
	'name' => "cullman",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_lkg2lk4x2nc3i',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_wzyfsfmvmfmvs',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_q1fphd13bide4',
	'label' => "Dale",
	'name' => "dale",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_z1ebh3qq0dgk0',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_g9yo7rc3x41ud',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_ztbv5pfp5luu4',
	'label' => "Dallas",
	'name' => "dallas",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_jcvvt1jicwdqa',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_7axanktyy5lsg',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_95jjwmezzn7l4',
	'label' => "De Kalb",
	'name' => "de kalb",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_qu0ia9vfgtg8s',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_4g61y9ew5cvs8',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_qjamq4tqxxd4s',
	'label' => "Elmore",
	'name' => "elmore",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_x0vwnyydo3scp',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_7kvmr27asbkmd',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_oe6wehvb0qd10',
	'label' => "Escambia",
	'name' => "escambia",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_xaezzwhp27b2j',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_prafqmli9lul3',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_67jc6sfn5pm8s',
	'label' => "Etowah",
	'name' => "etowah",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_fm8sgj97ahgg5',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_e3kvixaqnfyh0',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_dx2c7n3mvti9d',
	'label' => "Fayette",
	'name' => "fayette",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_33uim35zobt2y',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_2nquficzftuyy',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_mn6p4os68l71s',
	'label' => "Franklin",
	'name' => "franklin",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_363olbor7eimu',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_141gm3rw9fakg',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_2f1grdxr1jvlp',
	'label' => "Geneva",
	'name' => "geneva",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_0fz5wdq67a5yy',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_18vq0kh9iead7',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_e21ilf7ppjku2',
	'label' => "Greene",
	'name' => "greene",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_mmlho0bgvuazl',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_yj60fpv08sc5j',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_wsmth923uzn21',
	'label' => "Hale",
	'name' => "hale",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_1esm0axphoj9q',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_588qa7htlr6ul',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_j8ey78pet064l',
	'label' => "Henry",
	'name' => "henry",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_n3zgg6whot03y',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_ur1qska087baf',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_jk2603xmpym88',
	'label' => "Houston",
	'name' => "houston",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_ullkadniov189',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_3q6fsdxfz9a38',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_0ovg1lbezavfe',
	'label' => "Jackson",
	'name' => "jackson",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_klotqiqqi3xtn',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_pxcrxyj6ptqp0',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_ucpg1v4jav69x',
	'label' => "Jefferson",
	'name' => "jefferson",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_a90mbzsh58k4i',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_zrv0qa1fbaczk',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_jtwksyedcul7u',
	'label' => "Lamar",
	'name' => "lamar",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_fnafh3tye1l12',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_4t43g5fmhh0zn',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_7werdwstszkxq',
	'label' => "Lauderdale",
	'name' => "lauderdale",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_vdqm4wzc93hx1',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_k510v0awgmsl5',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_bqyt1w28ildrm',
	'label' => "Lawrence",
	'name' => "lawrence",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_s04k99pn9tcrc',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_vy82uee4br5o1',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_pf3xub9cx57kt',
	'label' => "Lee",
	'name' => "lee",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_z1v9vr95vpq2n',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_wyns3mwsqzjpi',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_4on3wg4kp7c7d',
	'label' => "Limestone",
	'name' => "limestone",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_chssj5owxgsoy',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_peo8z02fumput',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_tnv1de3tas6jq',
	'label' => "Lowndes",
	'name' => "lowndes",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_8w0oub0n4c455',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_ploef2ikwbpvg',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_o4rwtggexosoy',
	'label' => "Macon",
	'name' => "macon",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_nxq01b5eonrs9',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_1gy2uql0b1vdv',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_126onqt36eu5k',
	'label' => "Madison",
	'name' => "madison",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_rb9oomd165z4o',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_2rqvsbtpcnyxi',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_ei6njzuhyopvx',
	'label' => "Marengo",
	'name' => "marengo",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_lig5yvj0a378q',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_1gz0kas3g9yll',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_bbmd6pzy7diq9',
	'label' => "Marion",
	'name' => "marion",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_d8staofcnadbf',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_imoqlzvgx7nh5',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_njndpxc29qicg',
	'label' => "Marshall",
	'name' => "marshall",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_m2ontukqo4ipo',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_4e1lmy3ah7bsv',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_wma6ju59l6bkd',
	'label' => "Mobile",
	'name' => "mobile",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_fzfpoy2in5lyq',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_pb51wy14bmg36',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_pev6pw4fuy96e',
	'label' => "Monroe",
	'name' => "monroe",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_4y9j34nrqk63e',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_1t4uog8dv23l7',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_vhev2touotck0',
	'label' => "Montgomery",
	'name' => "montgomery",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_6x4aijs5iz7b7',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_3s91iu6c69p30',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_rp2prrkm098al',
	'label' => "Morgan",
	'name' => "morgan",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_72jaxu540q8ru',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_y62iey6v6rugc',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_vm7xgjgjrx45s',
	'label' => "Perry",
	'name' => "perry",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_9tj1oyjqadbzn',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_zu6i0u33dc7xe',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_ncw2iz9o730p3',
	'label' => "Pickens",
	'name' => "pickens",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_9n2dt21qos7r4',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_9sd8qv6ctqdsv',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_25t1tnq5k9jkv',
	'label' => "Pike",
	'name' => "pike",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_3crflc3yeok2f',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_09ofoenhzf7wg',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_76qmx93jkcfvq',
	'label' => "Randolph",
	'name' => "randolph",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_xuzzyz0dj65hi',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_w44tkxnl4ispv',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_hvv65y13lxy7y',
	'label' => "Russell",
	'name' => "russell",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_hsoezjpunsm9e',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_3qfgyd66zkvsl',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_dnbomgou7hrqu',
	'label' => "St. Clair",
	'name' => "st. clair",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_ichgi7r550zxz',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_bez6tswyyf3kl',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_ti2ulh8fhd879',
	'label' => "Shelby",
	'name' => "shelby",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_i3su5ba1m9t4j',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_ccsttmp90vzxx',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_qqgaancgkrvcx',
	'label' => "Sumter",
	'name' => "sumter",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_tkn95th2o8kqk',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_jwlp7u8leeeff',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_fb5yo9cthvvy5',
	'label' => "Talladega",
	'name' => "talladega",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_a7rrrh8tw9bzf',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_wukxf7lyqkyui',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_czff4rf8fiz2c',
	'label' => "Tallapoosa",
	'name' => "tallapoosa",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_aabxxkan6nch6',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_ku99jgxg0wbln',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_7r24jyoujtr6m',
	'label' => "Tuscaloosa",
	'name' => "tuscaloosa",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_e0aaxzu0qc3n1',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_i2owdf0p3pxon',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_7z63muoh7ghv8',
	'label' => "Walker",
	'name' => "walker",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_7euvv32xqfnlm',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_x1clg6xofcgos',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_zcxr1xzluszmz',
	'label' => "Washington",
	'name' => "washington",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_7wyiv5ku83q3r',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_o9hiwn8rshwee',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_zjfuss4p52e45',
	'label' => "Wilcox",
	'name' => "wilcox",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_wkqfxbv5de8k4',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_vn0yd07yumytn',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
),
array(
	'key' => 'field_8c6u2lho4zjgo',
	'label' => "Winston",
	'name' => "winston",
	'type' => 'group',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	) ,
	'layout' => 'table',
	'sub_fields' => array(
		array(
			'key' => 'field_jjqlvkt8cgzwk',
			'label' => 'Data',
			'name' => 'data',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'message' => '',
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		) ,
		array(
			'key' => 'field_yydvkj5dscz2w',
			'label' => 'Page',
			'name' => 'page',
			'type' => 'page_link',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			) ,
			'post_type' => array(
				0 => 'page',
			) ,
			'taxonomy' => array() ,
			'allow_null' => 0,
			'allow_archives' => 0,
			'multiple' => 0,
		) ,
	) ,
) ,
